name = "log-tail-service"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# D1 Database for log metadata and configuration
[[d1_databases]]
binding = "DB"
database_name = "log-tail"
database_id = "723535ee-4f71-4b36-b262-0bc8c0a0f9f5"  # Replace with actual database ID after creation

# R2 for full log archive
[[r2_buckets]]
binding = "LOGS_ARCHIVE"
bucket_name = "log-tail-archive"

# AI binding for agentic analysis
[ai]
binding = "AI"

# Environment variables
[vars]
DEFAULT_TTL_DAYS = "30"
ENABLE_WEBSOCKET = "true"
CLEANUP_BATCH_SIZE = "1000"

# Secrets (set with: wrangler secret put LOG_SERVICE_API_KEY)
# LOG_SERVICE_API_KEY = "your-secret-key"

# Cron triggers for cleanup and daily global analysis
[triggers]
crons = [
    "0 2 * * *",   # Daily cleanup at 2 AM
    "0 3 * * *"    # Daily global analysis at 3 AM
]

# Durable Objects for analysis state management
[[durable_objects.bindings]]
name = "ANALYSIS_AGENT"
class_name = "AnalysisAgent"

[[migrations]]
tag = "v1"
new_classes = ["AnalysisAgent"]

# Queue for background analysis jobs
[[queues.producers]]
queue = "log-tail-analysis"
binding = "ANALYSIS_QUEUE"

[[queues.consumers]]
queue = "analysis-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3

# Assets binding for React frontend
[assets]
directory = "./public"
binding = "ASSETS"

# Enable observability (optional - for monitoring the logging service itself)
[observability]
enabled = true
head_sampling_rate = 0.1
